### ISSUE TITLE
block.py - convert function documentation comments to reST format

### ISSUE THREAD

**Issue by wilt00** [SIGBlockchain/Project#1]
Currently, we're documenting functions like this:

```python
# My function
def my_function(param1, param2):
    ...
```

If we document them using the ReStructuredText format, we can use a tool like Sphinx to generate pretty HTML documentation automatically. That would look like this:

```python
def my_function(param1, param2):
    """
    This is a reST style.

    :param param1: this is a first param
    :param param2: this is a second param
    :returns: this is a description of what is returned
    :raises keyError: raises an exception
    """
    ...
```

**Comment by kstola2** [comment]
We will now make this part of each story once we start building. I dig it!

**Comment by kstola2** [comment]
We should also consider doing a sweep of all functions and carefully renaming everything according to PEP8 standards, but I may make that into a separate story.

https://www.python.org/dev/peps/pep-0008/

**Comment by ramirez915** [comment]
Can I take on this story for the remaining functions?

**Comment by kstola2** [comment]
@ramirez915 I sent you an invite to the organization go ahead and accept it and take the story.

**Comment by ramirez915** [comment]
Not sure where to accept but I will work on it, thank you!

**Comment by kstola2** [comment]
@ramirez915 I think it should send you an email
