### ISSUE TITLE
Connection Status Field

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project#13]
Given a boolean representing the node's connection status as an argument, display it as a string in the GUI window. Should say "Online"/"Offline" depending on what is the state of the boolean. 

Placement should be similar to the picture.

![tentative_gui](https://user-images.githubusercontent.com/31855040/46900494-a67e0f00-ce68-11e8-8213-a3ffa53708cd.jpg)

**Comment by Vineet77** [comment]
Attempted this, check pull request.
