### ISSUE TITLE
Convert dictionary function returns to namedtuple

### ISSUE THREAD

**Issue by wilt00** [SIGBlockchain/Project#2]
The functions `createBlock` and `createBlockPoW` return dictionaries with several values. To access these values, we need to pass in a string key. This process cannot be error-checked. Additionally, we don't actually want other places in the codebase to be able to add more keys to this dictionary, or change the values of the keys that are present.

Instead, we might consider converting these to namedtuples instead. See here (https://stackoverflow.com/questions/9872255/when-and-why-should-i-use-a-namedtuple-instead-of-a-dictionary#9872434) for a comparison.

**Comment by wilt00** [comment]
I've done some more research, and it turns out that, while namedtuple is really convenient and used all over the Python codebase, it's also pretty slow compared with regular dictionaries. See benchmarks [here ](https://rhye.org/post/python-cassandra-namedtuple-performance/) and discussion of alternatives [here](https://stackoverflow.com/questions/354883/how-do-you-return-multiple-values-in-python). Probably not worth switching over, when there's more important work to be done elsewhere.

**Comment by kstola2** [comment]
Currently the dictionary implementation is simply a matter of understanding the results visually and getting everyone familiar with the data structure. There's an even better way to store block information, and that's in the form of a parse-able byte string. Which is what SIG BC was doing last semester and what we plan to do once again this semester after bringing everyone up to speed.
