### ISSUE TITLE
log_target_bytes

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project#21]
Given an unsigned base-10 whole number, find the base-10 log of that number and return the result as a short in byte form.

Use the `log10()` function from the Python `math` library and our short_to_byte function in `block.py`.

This function will go in `block.py` at the bottom, and tests will go in `block.test.py`.
Use the documentation standards shown here: [https://github.com/SIGBlockchain/Project/issues/1](url)

**Comment by ramirez915** [comment]
I'll work on this one if it's still available
