### ISSUE TITLE
Layout Manager

### ISSUE THREAD

**Issue by Vineet77** [SIGBlockchain/Project#28]
Before we start adding things to the UI, we need to set up a layout manager. Layout managers position widgets for us rather than us specifying the absolute position. Layout managers are a necessity for any decent graphical user interface. For pyQt, the most used and versatile layout is the QGridLayout.

Set up a QGridLayout in the UI.py and position the title to the top center. If it all works out, if you resize the window, the title will still stay in the center. 

Here is the documentation for QGridLayout: http://pyqt.sourceforge.net/Docs/PyQt4/qgridlayout.html
Here is a nice tutorial: https://www.tutorialspoint.com/pyqt/pyqt_qgridlayout_class.htm

If you have any other layout you think would work, please recommend!

**Comment by kstola2** [comment]
May I suggest making a separate file in the user_interface folder for now, just so that it's separate from existing code.

**Comment by Vineet77** [comment]
So like a copy of ui.py? The layout part would be in the ui.py or which every python file defines the GUI.

**Comment by kstola2** [comment]
I see what you did. It works.
