### ISSUE TITLE
slice_nonce

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project#40]
Our mine function will return a single byte string representing a collection of valuable metadata. We will need a way to extract this information, given just the byte string. 

Byte strings are similar to regular strings in the sense they can be indexed. Python uses a method called _slicing_ which allows you to pluck out a certain section of contiguous bytes. Since we know the order in which our metadata was concatenated in the mine function, we can slice out whatever we need.

Quick Guide to Slicing: [http://www.datadependence.com/2016/05/python-sequence-slicing-guide/](url)

The image shows what the block header looks like, and each colored section represents a different piece of metadata.

![image](https://user-images.githubusercontent.com/31855040/47131967-2fc98300-d267-11e8-9a1c-aa784d34ffc3.png)

Write a function that takes a `block_header `as a parameter (which is a concatenated byte string of length 74) and returns the purple section, which is the block header's `nonce`. 

NOTE: Do not omit endpoints. 

This function should go in `block.py`, with tests going in `block.test.py`.
Documentation follows the same standard as previous issues.

**Comment by arosso3** [comment]
I'll attempt this

**Comment by kstola2** [comment]
I will be reopen this once the mine function is completed.
