### ISSUE TITLE
int_to_bytes

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project#6]
Given an integer `i`, return it as an unsigned integer in byte form.

Use the `pack` function from the Python `struct` library to convert data into bytes.

Refer to the table to match up the correct C type with the Python type or just check it at out [https://docs.python.org/3/library/struct.html](url)

NOTE: it is imperative to use the unsigned versions.

This function will go in the` block.py` file and the tests will go in the `block.test.py` file, both located in the data_structures folder. Code must be commented in the reST format shown in this issue: [https://github.com/SIGBlockchain/Project/issues/1](url)

If there are any questions, please post them as comments below.

![struct table](https://user-images.githubusercontent.com/31855040/46676829-f037d280-cba6-11e8-96b6-ec1e3457ed80.PNG)

**Comment by Vineet77** [comment]
I'll take this on

**Comment by Vineet77** [comment]
When you say given a signed int, are negative numbers gonna be given? Because the pack() method won't work with negative values if you give it the 'I' format for unsigned int.

**Comment by Vineet77** [comment]
"When packing a value x using one of the integer formats ('b', 'B', 'h', 'H', 'i', 'I', 'l', 'L', 'q', 'Q'), if x is outside the valid range for that format then struct.error is raised."
