### ISSUE TITLE
user interface window

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project#7]
The project needs a GUI. **PyQt** is a native user-interface application development tool for Python. 
There are many tutorials and documentation on how to use PyQt online. For this story, the `ui.py` file located in the user_interface folder will be edited. To keep it simple, write some lines of code that will generate a window that simply says "SIG Blockchain Project" at the top. There are no tests needed at the moment, since this is a just a visual confirmation that is works.

Feel free to comment any sources or tutorials as suggestions or if they were used.

**Comment by bashbashbash** [comment]
Interested in attempting this

**Comment by bashbashbash** [comment]
I am ready to review this item

**Comment by kstola2** [comment]
Completed!
